language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jaworskg/docker-tutorial-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaworskg/docker-tutorial-react npm run test